# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    interbotix_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    interbotix_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

interbotix_arm_controller:
  ros__parameters:
    joints:
      - waist
      - shoulder
      - elbow
      - wrist_angle
      - wrist_rotate
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
interbotix_gripper_controller:
  ros__parameters:
    joints:
      - left_finger
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity